# Generated by Django 5.1.5 on 2025-01-24 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('cuisine', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('atmosphere', models.CharField(choices=[('Fine Dining', 'Fine Dining'), ('Casual', 'Casual'), ('Family-Friendly', 'Family-Friendly'), ('Cafe', 'Cafe')], max_length=255)),
                ('hours_of_operation', models.TextField()),
                ('delivery_options', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('Teens', 'Teens'), ('Young Adults', 'Young Adults'), ('Families', 'Families'), ('Seniors', 'Seniors')], max_length=255)),
                ('income_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=255)),
                ('preferences', models.TextField(help_text='Dietary preferences or dining habits.')),
                ('engagement_platforms', models.TextField(help_text='Preferred social media platforms (e.g., Instagram, LinkedIn).')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_audience', to='restaurant.restaurant')),
            ],
        ),
    ]
